name: Python & Airflow CI

on: [push, pull_request]

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Black (formatter check)
      run: black . --check

    - name: Run Flake8 (style + error check)
      run: flake8 .

    - name: Validate Airflow DAGs (optional)
      run: |
        mkdir -p dags
        python -c "from airflow.models.dagbag import DagBag; DagBag(dag_folder='dags')"
